stages:
   - build
   - deploy

build react-app:
  image: node:14.19-alpine3.14 
  stage: build 
  only:    
    - main
    - develop
    - stage
  script:
    - apk add --no-cache python2
    - yarn
    - yarn build
  artifacts:
    paths:
      - ./build 
    expire_in: 1 hour
  tags:
    - build

deploy develop:
  image: python:latest
  stage: deploy
  only:
    - develop
  script:
    - pip3 install awscli
    - aws s3 sync ./build s3://pocker-frontend-develop
  tags: 
  - deploy

  deploy stage:
  image: python:latest
  stage: deploy
  only:
    - stage
  script:
    - pip3 install awscli
    - aws s3 sync ./build s3://pocker-frontend-stage
  tags: 
  - deploy