stages:
   - build
   - deploy
varibeks: 
  target: $CI_COMMIT_REF_NAME

build react-app:
  image: node:14.19-alpine3.14 
  stage: build 
  only:    
    - main
    - develop
    - stage
  script:
    - apk add --no-cache python2
    - yarn
    - yarn build
  artifacts:
    paths:
      - ./build 
    expire_in: 1 hour
  tags:
    - build

deploy :
  image: python:latest
  stage: deploy
  only:
    - main
    - develop
    - stage
  script:
    - pip3 install awscli
    - aws s3 sync ./build s3://pocker-frontend-{{target}}
  tags: 
    - deploy