---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_port: 22
    ansible_connection: ssh

project:
  hosts:
    main:
      ansible_host: 
      ansible_user: ubuntu
    
    stage:
      ansible_host: 34.220.245.116
      ansible_user: ubuntu
    # dev - version

    develop:
      ansible_host: 
      ansible_user: ubuntu
    # prod - version