import type { Action } from 'types';

export type ApiAction = Action<'CONNECT_TO_WS'>;

export enum WsGameTypes {
  WS_CONNECT = 'WS_GAME_CONNECT',
  WS_DISCONNECT = 'WS_GAME_DISCONNECT',
  WS_CONNECTED = 'WS_GAME_CONNECTED',
  WS_DISCONNECTED = 'WS_GAME_DISCONNECTED',
  WS_MESSAGE = 'WS_GAME_MESSAGE',
  WS_SEND_MESSAGE = 'WS_GAME_SEND_MESSAGE',
}

export enum WsRateTypes {
  WS_CONNECT = 'WS_RATE_CONNECT',
  WS_DISCONNECT = 'WS_RATE_DISCONNECT',
  WS_CONNECTED = 'WS_RATE_CONNECTED',
  WS_DISCONNECTED = 'WS_RATE_DISCONNECTED',
  WS_MESSAGE = 'WS_RATE_MESSAGE',
  WS_SEND_MESSAGE = 'WS_RATE_SEND_MESSAGE',
}
